### ISSUE TITLE
Improvement :Using docker for deploying and creating build package

### ISSUE THREAD

**Issue by darthvader2** [strattyx/day-of-week-extension#1]
**Background**
Flask-weekday-extension is currently deployed on organically on the servers. local development Environments will be different from the production environment this will cause issues while deploying different services on a server.   

**Desired change**
Docker provides a convenient way to have local development environments that closely match the production.

**Comment by dvtate** [comment]
- This example assumes user self-hosts and is designed to be fairly generic in terms of timezones and such. Wanted this example to be extremely simple
- One main use if the extension feature is for individuals/companies who have their own proprietary data sources they would like to use with our platform but don't want us to use
- Will probably make a docker version eventually

**Comment by dvtate** [comment]
- Adding a deployment section to readme which will include all the dependencies and some steps for running it
- I think since this example is like 50SLOC of Python it shouldn't need docker, but I think when we make a more complicated example then we will have to
